name: Upstream Sync

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  sync_latest_from_upstream:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.5
        with:
          upstream_sync_repo: cmliu/edgetunnel
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      # 👉 关键：触发 Cloudflare Pages
      - name: Force deploy
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git commit --allow-empty -m "trigger deploy"
          git push
